name: Cppcheck + Reviewdog

on: [push, pull_request]

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install cppcheck
        run: sudo apt-get update && sudo apt-get install cppcheck -y

      - name: Run cppcheck
        run: |
          cppcheck --enable=all --inconclusive --xml --xml-version=2 ./ 2> cppcheck-result.xml

      - name: Run reviewdog
        uses: reviewdog/action-reviewdog@v2
        with:
          name: cppcheck
          tool_name: cppcheck
          reporter: github-pr-review
          filter_mode: diff_context
          fail_on_error: true
          level: error
          input: cppcheck-result.xml
          input_format: cppcheck
