name: Cppcheck CI

on: [push, pull_request]

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install cppcheck
        run: sudo apt-get update && sudo apt-get install cppcheck -y

      - name: Run cppcheck
        run: cppcheck --enable=all --inconclusive --quiet --error-exitcode=1 .
